### PR TITLE
Bug Fixed: stream not closed if empty and destroy not called

### PR DESCRIPTION
**Pull request by shreyancejain**
If destroy method is not called and buffer become empty, stream should destroy itself.

### CODE REVIEW

**Comment by samcday** [comment]
Hi @shreyancejain - thanks for the contribution. [Looks like some tests are failing though](https://travis-ci.org/samcday/node-stream-buffer/builds/72311200), do you know what that's all about?

**Comment by shreyancejain** [comment]
Hi @samcday  - Sorry for that, Its my bad, I forgot to update test cases after my change. Now all tests are passing.

**Comment by shreyancejain** [comment]
Actually **destroySoon** now actually destroys the stream and not waiting for stream to end, I think that should be the behavior of **destroySoon**.

**Comment by samcday** [comment]
Hmmm okay I see what you're trying to do here. Not sure I agree with the change though. If you want this behaviour you can simply write the data you want to the stream and then call `destroySoon()` to ensure it ends once that data has been emitted to consumers.

**Comment by shreyancejain** [comment]
Hmmm okay that could be done, I thought in a different way, thanks for clarification.....:)

**Pull request closed without merging**
